---
name: Play Sound
version: dev
slug: playsound
description: Module to play an audio file on a local audio interface.
url: https://github.com/joosthb/hassio-addons
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
audio: true
init: false